### ISSUE TITLE
Cannot find module express

### ISSUE THREAD

**Issue by marlenesco** [MMelchiorri/task_verisure#1]
Ciao @MMelchiorri ,
ho provato a far partire il container ma da questo errore:

```
task_verisure-your-service-name-1: > task_verisure@1.0.0 start /usr/code
task_verisure-your-service-name-1: > node index.js
task_verisure-your-service-name-1: 
task_verisure-your-service-name-1: internal/modules/cjs/loader.js:934
task_verisure-your-service-name-1:   throw err;
task_verisure-your-service-name-1:   ^
task_verisure-your-service-name-1: 
task_verisure-your-service-name-1: Error: Cannot find module 'express'
task_verisure-your-service-name-1: Require stack:
task_verisure-your-service-name-1: - /usr/code/index.js
task_verisure-your-service-name-1:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
task_verisure-your-service-name-1:     at Function.Module._load (internal/modules/cjs/loader.js:774:27)
task_verisure-your-service-name-1:     at Module.require (internal/modules/cjs/loader.js:1003:19)
task_verisure-your-service-name-1:     at require (internal/modules/cjs/helpers.js:107:18)
task_verisure-your-service-name-1:     at Object.<anonymous> (/usr/code/index.js:1:17)
task_verisure-your-service-name-1:     at Module._compile (internal/modules/cjs/loader.js:1114:14)
task_verisure-your-service-name-1:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
task_verisure-your-service-name-1:     at Module.load (internal/modules/cjs/loader.js:979:32)
task_verisure-your-service-name-1:     at Function.Module._load (internal/modules/cjs/loader.js:819:12)
task_verisure-your-service-name-1:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
task_verisure-your-service-name-1:   code: 'MODULE_NOT_FOUND',
task_verisure-your-service-name-1:   requireStack: [ '/usr/code/index.js' ]
task_verisure-your-service-name-1: }
task_verisure-your-service-name-1: npm ERR! code ELIFECYCLE
task_verisure-your-service-name-1: npm ERR! errno 1
task_verisure-your-service-name-1: npm ERR! task_verisure@1.0.0 start: `node index.js`
task_verisure-your-service-name-1: npm ERR! Exit status 1
task_verisure-your-service-name-1: npm ERR! 
task_verisure-your-service-name-1: npm ERR! Failed at the task_verisure@1.0.0 start script.
task_verisure-your-service-name-1: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
task_verisure-your-service-name-1: npm WARN Local package.json exists, but node_modules missing, did you mean to install?
task_verisure-your-service-name-1: 
task_verisure-your-service-name-1: npm ERR! A complete log of this run can be found in:
task_verisure-your-service-name-1: npm ERR!     /root/.npm/_logs/2023-11-16T16_10_27_865Z-debug.log
```
Credo che il problema sia non esista un modo per fare `npm install` esternamente al container.
Credo serva un comando esterno che agisca sul container.
Ciao
d

**Comment by MMelchiorri** [comment]
@marlenesco ora purtroppo sto partendo posso provare a vedere se ho un PC a disposizione e provo a vedere. Ma non so se ha docker installato. Scusami

**Comment by marlenesco** [comment]
Non preoccuparti Marco, quando puoi, stavo solo dando un'occhiata al codice mi sono già fatto un'idea sull'approccio al problema e direi che è buono.
Buon WE

**Comment by MMelchiorri** [comment]
Grazie, buon weekend anche a te

**Comment by MMelchiorri** [comment]
Ciao David, ho modificato il docker compose file aggiungendo un ulteriore volume       - /usr/code/node_modules. Se fai un pull oppure aggiungi questa riga al volume in docker compose dovrebbe funzionare

**Comment by marlenesco** [comment]
Ciao Marco, perfetto, grazie
